export const coachingCenters = [
    {
      name: 'Retina Coaching Center',
      image: '/Assets/class_room_course.svg',
      location: 'Mirpur DOHS, MIST',
      rating: 4.6,
      students: 2000,
      teachers: 50,
      courses: 10,
    },
    {
      name: 'Udvash Unmesh Coaching Center',
      image: '/Assets/class_room_course.svg',
      location: 'Mirpur DOHS, MIST',
      rating: 4.2,
      students: 4000,
      teachers: 50,
      courses: 10,
    },
    {
      name: 'Mayer Dowa Coaching Center',
      image: '/Assets/class_room_course.svg',
      location: 'Mirpur DOHS, MIST',
      rating: 2.5,
      students: 200,
      teachers: 5,
      courses: 10,
    },
    {
      name: 'Newton Coaching Center',
      image: '/Assets/class_room_course.svg',
      location: 'Mirpur DOHS, MIST',
      rating: 4.6,
      students: 20,
      teachers: 50,
      courses: 10,
    },
    {
      name: 'Elon Mask Coaching Center',
      image: '/Assets/class_room_course.svg',
      location: 'Mirpur DOHS, MIST',
      rating: 4.9,
      students: 20000,
      teachers: 500,
      courses: 1,
    },
    {
      name: 'Goal Engineering Coaching Center',
      image: '/Assets/class_room_course.svg',
      location: 'Mirpur DOHS, MIST',
      rating: 4.6,
      students: 2000,
      teachers: 50,
      courses: 10,
    },
  ]