export const coachingCenters = [
  {
    name: 'Retina Coaching Center',
    id: '1234',
    image: '/Assets/class_room_course.svg',
    location: 'Mirpur DOHS, MIST',
    rating: 4.6,
    students: 2000,
    teachers: 50,
    courses: 10,
  },
  {
    name: 'Udvash Unmesh Coaching Center',
    id: '123da',
    image: '/Assets/class_room_course.svg',
    location: 'Mirpur DOHS, MIST',
    rating: 4.2,
    students: 4000,
    teachers: 50,
    courses: 10,
  },
  {
    name: 'Mayer Dowa Coaching Center',
    id: '123dk',
    image: '/Assets/class_room_course.svg',
    location: 'Mirpur DOHS, MIST',
    rating: 2.5,
    students: 200,
    teachers: 5,
    courses: 10,
  },
  {
    name: 'Newton Coaching Center',
    id: '123dz',
    image: '/Assets/class_room_course.svg',
    location: 'Mirpur DOHS, MIST',
    rating: 4.6,
    students: 20,
    teachers: 50,
    courses: 10,
  },
  {
    name: 'Elon Mask Coaching Center',
    id: '523dz',
    image: '/Assets/class_room_course.svg',
    location: 'Mirpur DOHS, MIST',
    rating: 4.9,
    students: 20000,
    teachers: 500,
    courses: 1,
  },
  {
    name: 'Goal Engineering Coaching Center',
    id: '5k3dz',
    image: '/Assets/class_room_course.svg',
    location: 'Mirpur DOHS, MIST',
    rating: 4.6,
    students: 2000,
    teachers: 50,
    courses: 10,
  },
]

export const courses = [
  {
    name: 'Physics',
    program: 'Class 5',
    image: '/Assets/class_room_course.svg',
    classes: 12,
    total_time: '15h 20m',
    students: 1500,
    price: 1800,
    rating: 3.2,
  },
  {
    name: 'Chemistry',
    program: 'HSC',
    image: '/Assets/class_room_course.svg',
    classes: 8,
    total_time: '12h 45m',
    students: 2200,
    price: 2500,
    rating: 4.7,
  },
  {
    name: 'Math',
    program: 'Class 9',
    image: '/Assets/class_room_course.svg',
    classes: 15,
    total_time: '20h 10m',
    students: 1800,
    price: 2100,
    rating: 2.3,
  },
  {
    name: 'Biology',
    program: 'Admission',
    image: '/Assets/class_room_course.svg',
    classes: 10,
    total_time: '18h 30m',
    students: 2000,
    price: 2300,
    rating: 4.6,
  },
  {
    name: 'English',
    program: 'Class 7',
    image: '/Assets/class_room_course.svg',
    classes: 9,
    total_time: '14h 50m',
    students: 1700,
    price: 1900,
    rating: 4.4,
  },
]

export const teacherMonitorDetails = [
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
  {
    teacher_name: 'Sagor',
    teacher_id: '121u2',
    total_class: 20,
    due_payment: 2000,
    rating: 4.5,
  },
]

export const studentMonitorDetails = [
  {
    name: 'Alice',
    total_course: 12,
    exam_performance: 85.3,
  },
  {
    name: 'Bob',
    total_course: 10,
    exam_performance: 78.1,
  },
  {
    name: 'Charlie',
    total_course: 15,
    exam_performance: 92.5,
  },
  {
    name: 'David',
    total_course: 8,
    exam_performance: 67.4,
  },
  {
    name: 'Eve',
    total_course: 14,
    exam_performance: 88.9,
  },
  {
    name: 'Frank',
    total_course: 11,
    exam_performance: 74.2,
  },
  {
    name: 'Grace',
    total_course: 13,
    exam_performance: 81.7,
  },
  {
    name: 'Hank',
    total_course: 9,
    exam_performance: 69.8,
  },
  {
    name: 'Ivy',
    total_course: 16,
    exam_performance: 95.4,
  },
]

export const routine = [
  {
    class: 1,
    date: '12 Jan 2024',
    time: '14:45',
    day: 'Monday',
    class_link: '#',
  },
  {
    class: 2,
    date: '13 Jan 2024',
    time: '14:45',
    day: 'Tuesday',
    class_link: '#',
  },
  {
    class: 3,
    date: '14 Jan 2024',
    time: '14:45',
    day: 'Wednesday',
    class_link: '#',
  },
  {
    class: 4,
    date: '15 Jan 2024',
    time: '14:45',
    day: 'Thursday',
    class_link: '#',
  },
  {
    class: 5,
    date: '16 Jan 2024',
    time: '14:45',
    day: 'Friday',
    class_link: '#',
  },
  {
    class: 6,
    date: '17 Jan 2024',
    time: '14:45',
    day: 'Saturday',
    class_link: '#',
  },
  {
    class: 7,
    date: '18 Jan 2024',
    time: '14:45',
    day: 'Sunday',
    class_link: '#',
  },
]

export const scriptEvaluation = [
  {
    sl_no: 1,
    script_id: '1234',
    student_name: 'Alice',
    student_email: 'alice@gmail.com',
    script: '/Assets/answerScript.svg',
  },
  {
    sl_no: 2,
    script_id: '1235',
    student_name: 'Bob',
    student_email: 'bob@gmail.com',
    script: '/Assets/answerScript.svg',
  },
  {
    sl_no: 3,
    script_id: '1236',
    student_name: 'Charlie',
    student_email: 'charlie@gmail.com',
    script: '/Assets/answerScript.svg',
  },
  {
    sl_no: 4,
    script_id: '1237',
    student_name: 'David',
    student_email: 'adf@gmail.com',
    script: '/Assets/answerScript.svg',
  },
  {
    sl_no: 5,
    script_id: '1238',
    student_name: 'Eve',
    student_email: 'eve@gmail.com',
    script: '/Assets/answerScript.svg',
  },
]

export const classPerformance = [
  {
    class: 1,
    reviews: 10,
    rating: 4.5,
    date: '12 Jan 2024',
  },
  {
    class: 2,
    reviews: 8,
    rating: 4.2,
    date: '13 Jan 2024',
  },
  {
    class: 3,
    reviews: 15,
    rating: 4.8,
    date: '14 Jan 2024',
  },
  {
    class: 4,
    reviews: 12,
    rating: 4.3,
    date: '15 Jan 2024',
  },
  {
    class: 5,
    reviews: 9,
    rating: 4.6,
    date: '16 Jan 2024',
  },
  {
    class: 6,
    reviews: 7,
    rating: 4.1,
    date: '17 Jan 2024',
  },
  {
    class: 7,
    reviews: 11,
    rating: 4.7,
    date: '18 Jan 2024',
  },
  {
    class: 8,
    reviews: 14,
    rating: 4.4,
    date: '19 Jan 2024',
  },
  {
    class: 9,
    reviews: 13,
    rating: 4.9,
    date: '20 Jan 2024',
  },
  {
    class: 10,
    reviews: 6,
    rating: 4.0,
    date: '21 Jan 2024',
  },
]
